### ISSUE TITLE
Benchmarking Configurations for SparkSubmit

### ISSUE THREAD

**Issue by radhikabajaj123** [apache/datafusion-benchmarks#14]
Hello,

I am using the following configurations for benchmarking:

>     --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog \
>     --deploy-mode cluster \
>     --driver-memory 32g \
>     --executor-memory 128g \
>     --executor-cores 18 \
>     --driver-cores 8 \
>     --num-executors 3 \
>     --conf spark.yarn.populateHadoopClasspath=false \
>     --conf spark.yarn.archive=$BENCH_HOME/$BENCH_DISTR.tgz \
>     --jars /root/datafusion-comet/spark/target/comet-spark-spark3.4_2.13-0.3.0-SNAPSHOT.jar \
>     --conf spark.driver.extraClassPath=/root/datafusion-comet/spark/target/comet-spark-spark3.4_2.13-0.3.0-SNAPSHOT.jar \
>     --conf spark.executor.extraClassPath=/root/datafusion-comet/spark/target/comet-spark-spark3.4_2.13-0.3.0-SNAPSHOT.jar \
>     --conf spark.plugins=org.apache.spark.CometPlugin  \
>     --conf spark.sql.extensions=org.apache.comet.CometSparkSessionExtensions \
>     --conf spark.comet.cast.allowIncompatible=true \
>     --conf spark.comet.dexec.shuffle.enabled=true \
>     --conf spark.comet.exec.shuffle.mode=auto \
>     --conf spark.comet.shuffle.enforceMode.enabled=true \
>     --conf spark.shuffle.manager=org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager \

I am receiving different results (with a significant deviation from what is reported on the [benchmarking](https://datafusion.apache.org/comet/contributor-guide/benchmark-results/tpc-h.html) page).

Are there any additional configurations required to optimize performance with Comet?

**Comment by andygrove** [comment]
Hi @radhikabajaj123, I don't monitor this repo, so I did not see this issue until now. 

We have a tuning guide that may be helpful: https://datafusion.apache.org/comet/user-guide/tuning.html

It looks like you have a typo here:

```
--conf spark.comet.dexec.shuffle.enabled=true
```

It looks like you are using Delta Lake? Comet does not have support for that.

**Comment by andygrove** [comment]
If you are still having issues, please consider filing an issue in the datafusion-comet repo and we would be happy to help! I will close this issue,
